### ISSUE TITLE
Error Expecting value: line 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by marcosmaia** [Mazyod/ethogram#4]
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)

It begins well after doing this and slows

**Comment by Mazyod** [comment]
This looks like a json error... Which ethos panel are you trying to monitor? (e.g. http://btceth.ethosdistro.com/)

**Comment by marcosmaia** [comment]
http://165d38.ethosdistro.com @Mazyod

**Comment by Mazyod** [comment]
Thanks for reporting, I can't load the JSON response in Python using `json.loads` for some reason... I'll dig deeper..

**Comment by Mazyod** [comment]
Ah, found the issue .. Apparently, it's illegal to have `\n` character within a JSON string, without escaping it first `\\n`. I'll submit a hotfix, let me know if it works for you.

**Comment by Mazyod** [comment]
I actually can't reproduce it on my environment 😞 I modified `test_network.py`, and it is working fine.
```python
class NetworkTests(unittest.TestCase):
    def test_fetch_all_rigs(self):
        network = Network()
        rigs = network.fetch_rigs("165d38")

        self.assertEqual(len(rigs), 19)
        self.assertEqual(rigs[0].name, "00dd5e")
```

**Comment by Mazyod** [comment]
Do you think you it has to do with Python version? I have 3.6.2

**Comment by marcosmaia** [comment]
Hi, I think so, my version of python-3.6.4

**Comment by marcosmaia** [comment]
str.replace('\n' , '\\n')  to treat json with no?

**Comment by Mazyod** [comment]
I wanted to reproduce the error first on the bot. I was only able to reproduce it through hardcoding.

**Comment by marcosmaia** [comment]
def send_message(self, text, chat_id, code=False):
        text = "```\n" + text + "\n```" if code else text  to  text = "``\n" + text + "\n``" if code else text 
        Bot.TELEGRAM_BOT.send_message(
            text=text,
            chat_id=chat_id,
            parse_mode=ParseMode.MARKDOWN)

worked

**Comment by marcosmaia** [comment]
I went back to what was and stopped giving the mistake. can be the encoding of the file here is utf-8 without BOM

**Comment by marcosmaia** [comment]
Stopped from the error, will that and the telegram server?

**Comment by Mazyod** [comment]
Sorry, I don't understand what you mean?

**Comment by marcosmaia** [comment]
is not giving this error any more

**Comment by Mazyod** [comment]
🎉 please reopen if necessary
